name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Git_Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: check
      run: |
        if [[ -n $(git diff --check HEAD^) ]]; then
          echo "You must remove whitespace before submitting a pull request"
          echo ""
          git diff --check HEAD^
          exit -1
        fi
      shell: bash
      
